In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a2=np.array([[1,2,3],[4,5,6]])

In [4]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3=[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]

In [11]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [12]:
a3=np.array(a3)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [15]:
a1>=a2

array([[ True,  True,  True],
       [False, False, False]])

In [16]:
a2>a1

array([[False, False, False],
       [ True,  True,  True]])

In [18]:
boolarr=a1>=a2

In [19]:
boolarr

array([[ True,  True,  True],
       [False, False, False]])

In [20]:
type(boolarr)

numpy.ndarray

In [21]:
boolarr.dtype

dtype('bool')

In [22]:
boolarr.ndim

2

In [23]:
a1>5

array([False, False, False])

In [24]:
a1>2

array([False, False,  True])

In [25]:
a2>3

array([[False, False, False],
       [ True,  True,  True]])

In [26]:
a2>2

array([[False, False,  True],
       [ True,  True,  True]])

In [27]:
a1==a1

array([ True,  True,  True])

In [28]:
a2==a1

array([[ True,  True,  True],
       [False, False, False]])

## 5.sorting of arrays